version: 2
jobs:
  lint:
    docker:
      # specify the version you desire here
      - image: particlekit/ansible-lint
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo 'password' > ~/ansible-secret.txt
      - run: pip install ansible
      - run: make update-vendor-force
      - run: make lint

  test:
    machine: true
    environment:
      PIPENV_VENV_IN_PROJECT: 1
    steps:
      - checkout
      # TODO once kitchen is removed, we can use a python docker instance
      # without having to manually install python.
      - run:
          name: install python
          command: |
            cd /opt/circleci/.pyenv/plugins/python-build/../.. && git pull && cd -
            pyenv install
      - run:
          name: install pipenv
          command: pip install -U pipenv
      # Restore cache and install python dependencies
      - restore_cache:
          keys:
            - v2-pipenv-{{ checksum "Pipfile.lock" }}
            - v2-pipenv-
      - run:
          name: install python dependencies
          command: pipenv sync --dev
      - save_cache:
          key: v2-pipenv-{{ checksum "Pipfile.lock" }}
          paths:
            - .venv
      # Restore cache and install ruby dependencies
      - restore_cache:
          keys:
            - v1-bundle-{{ checksum "Gemfile.lock" }}
            - v1-bundle-
      - run:
          name: Install dependencies
          command: bundle install --path vendor/bundle
      - save_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Setup ansible-galaxy
          command: pipenv run make update-vendor-force
      - run:
          name: Run tests
          command: |
            TEST_TARGETS=$(make circleci-glob | circleci tests split)
            pipenv run make ${TEST_TARGETS}


workflows:
  version: 2
  commit:
    jobs:
      - lint
      - test
